name: Web automated testing with Selenium, Java, and GitHub Actions
run-name: Pipeline Selenium
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Install Chrome
        uses: nanasess/setup-chromedriver@v2.2.2

      - name: Run test
        run: mvn test -Dcucumber.filter.tags="@login"

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            /home/runner/work/robot-github-actions/target/evidence.html
            /home/runner/work/robot-github-actions/target/evidence.json