name: Web automated testing with Selenium, Java, and GitHub Actions
run-name: Pipeline Selenium
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

      - name: Install Chrome
        uses: nanasess/setup-chromedriver@v2.2.2

      - name: Run test
        run: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/x64/bin/java -Dmaven.multiModuleProjectDirectory=/home/runner/work/selenium-github-actions -Djansi.passthrough=true -Dmaven.home=/usr/local/lib/apache-maven-3.8.1 -Dclassworlds.conf=/usr/local/lib/apache-maven-3.8.1/bin/m2.conf -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 test

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            /home/runner/work/robot-github-actions/target/evidence.html
            /home/runner/work/robot-github-actions/target/evidence.json